version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
    groups:
      actions:
        patterns:
          - "actions/*"
      github:
        patterns:
          - "github/*"
      ossf:
        patterns:
          - "ossf/*"
      step-security:
        patterns:
          - "step-security/*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
    groups:
      kubernetes-dependencies:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"