version: "2"
linters:
  default: all
  disable:
    # Whitespace/style (too opinionated)
    - wsl
    - wsl_v5
    - nlreturn
    - lll

    # Naming (too restrictive)
    - varnamelen
    - ireturn

    # Complexity (better via code review)
    - funlen
    - cyclop
    - gocognit
    - maintidx

    # Struct initialization (too strict)
    - exhaustruct

    # Error handling (too dogmatic for library code)
    - err113
    - noinlineerr
    - forcetypeassert
    - wrapcheck

    # Testing (context-dependent)
    - paralleltest
    - gochecknoglobals

    # Project-specific (not needed)
    - depguard
    - forbidigo

    # Linters to potentially revisit
    - mnd
  exclusions:
    rules:
      - path: '.*_test\.go$'
        linters:
          - mnd
          - revive
      - path: pkg/resources/gvks/gvks\.go
        linters:
          - revive
          - gochecknoglobals

  settings:
    revive:
      enable-all-rules: true
      rules:
        # Disable noisy rules that don't add value
        - name: package-comments
          disabled: true
        - name: dot-imports
          disabled: true
        - name: var-naming
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: add-constant
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - prefix(k8s.io)
        - blank
        - prefix(github.com/lburgazzoli/gomega-matchers)
        - blank
        - dot
      custom-order: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0