version: "2"
linters:
  default: all
  disable:
    # Whitespace/style (too opinionated)
    - wsl
    - wsl_v5
    - nlreturn
    - lll

    # Naming (too restrictive)
    - varnamelen
    - ireturn

    # Complexity (better via code review)
    - funlen
    - cyclop
    - gocognit
    - maintidx
    - nestif

    # Struct initialization (too strict)
    - exhaustruct

    # Error handling (too dogmatic for library code)
    - err113
    - noinlineerr
    - forcetypeassert
    - wrapcheck

    # Testing (context-dependent)
    - paralleltest
    - gochecknoglobals

    # Project-specific (not needed)
    - depguard
    - forbidigo

    # Linters to potentially revisit
    - revive
    - mnd

formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - prefix(k8s.io)
        - blank
        - prefix(github.com/lburgazzoli/gomega-matchers)
        - blank
        - dot
      custom-order: true